services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "sed -i 's/localhost:15432/postgres/g' /workspace/.env && sleep infinity"
    volumes:
      - ..:/workspace:cached
      - try-node-node_modules:/workspace/node_modules
    depends_on: 
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 15432:5432

volumes:
  try-node-node_modules: